name: 'Download and extract Hugo'
description: 'Downloads and extracts a specified version of Hugo'
inputs:
  hugo_version:
    description: 'Version of Hugo to download'
    required: false
    default: '0.145.0'
runs:
  using: 'composite'
  steps:
    - name: Cache Hugo
      uses: actions/cache@v3
      with:
        path: ./hugo-bin
        key: ${{ runner.os }}-hugo-${{ inputs.hugo_version }}
    - name: Download and extract Hugo
      run: |
        make ./hugo-bin/.v${{ inputs.hugo_version }}
      shell: bash