name: "Deploy a branch version of the website"

on:
  pull_request:

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Skip workflow for PRs from forks
        shell: bash
        run: |
          if [ "${{ github.event.pull_request.head.repo.fork }}" = "true" ]; then
            echo "This workflow is not supported for PRs from forks."
            exit 0
          fi

      - name: Extract branch name
        shell: bash
        run: echo "BRANCH_NAME=$(echo ${{ github.head_ref }} | sed 's/\//-/g')" >> $GITHUB_ENV

      - name: Debug print branch name
        shell: bash
        run: echo "BRANCH_NAME=${{ env.BRANCH_NAME }}"

      - name: Setup Node.js
        uses: actions/setup-node@v5
        with:
          node-version: '24'

      - name: Install dependencies
        run: |
          npm install
          npm install -D autoprefixer postcss postcss-cli postcss-import tailwindcss tailwindcss-cli

      - name: Setup Hugo
        uses: ./.github/actions/setup-hugo

      - name: Setup PageFind
        uses: ./.github/actions/setup-pagefind

      - name: Build the website
        run: BASEURL="https://webtest.ivoa.info/v/${{ env.BRANCH_NAME }}" make html

      - name: Upload the branch version of the website
        uses: ./.github/actions/sftp-upload
        with:
          username: ${{ secrets.SFTP_STAGE_USER }}
          server: ${{ secrets.SFTP_STAGE_SERVER }}
          port: ${{ secrets.SFTP_STAGE_PORT }}
          key: ${{ secrets.SFTP_STAGE_KEY }}
          local_path: ./public
          remote_path: ${{ secrets.SFTP_VERSION_PATH }}/${{ env.BRANCH_NAME }}
